runtime: custom
env: flex
service: default
threadsafe: yes

network:
  forwarded_ports:
    - 80:8080

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20